### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Arnold1** [SamSaffron/graphite_docker#28]
hi,

how to start your docker only with Graphite + Carbon and not start Statsd + Grafana?
would it work if i only forward the related ports for Graphite + Carbon?
```
  graphite:
    image: samsaffron/graphite
    ports:
      - "2003:2003"
      - "2004:2004"
      - "7002:7002"
      - "8080:80"
    restart: always
```

how can i connect graphite-exporter to Graphite using your docker?

Thanks,
Arnold
